import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Settingprovider from '@/app/context/SettingContext';
import Content from "./content/Content";
import { IqProvider } from "./(private)/Iqcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <IqProvider>
          <Settingprovider>
            <Content>{children}</Content>
          </Settingprovider>
        </IqProvider>

      </body>
    </html>
  );
}
